title: Callum Stott
url: https://seadowg.com
description: Callum Stott is a senior software engineer and XP/Lean consultant with a focus on Android and full stack web development based in London.

plugins:
  - jekyll-feed

# Include these files/folders that are excluded by default
include: [ "/.well-known" ]

exclude:
  - scripts
