title: Callum Stott
url: https://seadowg.com
description: Callum Stott is a senior software engineer and XP/Lean consultant with a focus on Android and full stack web development based in London.

plugins:
  - jekyll-feed

exclude:
  - scripts
